on:
  push:
    branches:
      - main

name: Latest Release

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Create Release
    runs-on: 'ubuntu-latest'
    permissions:
      contents: write
    strategy:
      matrix:
        goosarch:
          - 'linux/amd64'
          - 'windows/amd64'
    steps:
      - name: set NOW
        run: |
          echo "NOW=$(date +'%Y%m%d%H')" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.6'
      - name: Get OS and arch info
        run: |
          GOOSARCH=${{matrix.goosarch}}
          GOOS=${GOOSARCH%/*}
          GOARCH=${GOOSARCH#*/}
          BINARY_NAME=HIBPDL-$GOOS-$GOARCH
          if [[ "$GOOS" == "windows" ]]; then
            BINARY_NAME="${BINARY_NAME}.exe"
          fi
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
          echo "GOOS=$GOOS" >> $GITHUB_ENV
          echo "GOARCH=$GOARCH" >> $GITHUB_ENV
      - name: Build
        run: |
          go build -ldflags '-extldflags "-static"' -o "$BINARY_NAME" -v ./cmd/HIBPDL
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          name: "${{ env.NOW }}"
          tag_name: "${{ env.NOW }}"
          draft: false
          prerelease: false
          files: |
            ./${{env.BINARY_NAME}}
          body: |
            # HIBPDL
            
            An alternative tool to download [HaveIBeenPwned](https://haveibeenpwned.com/) pwned password hash lists.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}